# Generated by Django 4.1.13 on 2024-03-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=225)),
                ('golongan', models.CharField(choices=[('pembina - I/A', 'pembina - I/A'), ('pembina - II/A', 'pembina - II/A'), ('pembina - III/A', 'pembina - III/A'), ('pembina - II/B', 'pembina - II/B'), ('pembina - I/A', 'pembina - I/A'), ('pembina - II/A', 'pembina - I/IA'), ('pembina - II/B', 'pembina - II/B'), ('pembina - III/C', 'pembina - III/C')], max_length=225)),
            ],
        ),
    ]
